const events = {
	0: {
		date: "01.01.2023",
		title: "New Year's Day",
		note: "Buy champagne",
		priority: "less important",
	},
	1: {
		date: "24.01.2023",
		title: "Day Grandmother and Grandfather",
		note: "Buy flowers and making a card",
		priority: "important",
	},
	2: {
		date: "09.02.2023",
		title: "My Birthday",
		note: "Buy cake",
		priority: "important",
	},
	3: {
		date: "14.02.2023",
		title: "Valentine Day",
		note: "Cook a delicious dinner",
		priority: "less important",
	},
	4: {
		date: "08.03.2023",
		title: "Women's Day",
		note: "Spa time",
		priority: "less important",
	},
	5: {
		date: "01.05.2023",
		title: "Labour Day",
		note: "Day off",
		priority: "important",
	},
	6: {
		date: "03.05.2023",
		title: "Constitution of May 3",
		note: "Procession in the market",
		priority: "important",
	},
	7: {
		date: "01.06.2023",
		title: "Children's Day",
		note: "Buy toys",
		priority: "less important",
	},
	8: {
		date: "01.08.2023",
		title: "National Day of Remembrance of the Warsaw Uprising",
		note: "Commemoration day",
		priority: "important",
	},
	9: {
		date: "09.04.2023",
		title: "EasterDay",
		note: "Prepare the eggs",
		priority: "less important",
	},
	10: {
		date: "11.11.2023",
		title: "National Independence Day",
		note: "procession through the city",
		priority: "important",
	},
	11: {
		date: "24.12.2023",
		title: "christmas eve",
		note: "Christmas dinner",
		priority: "important",
	},
	12: {
		date: "25.12.2023",
		title: "Christmas",
		note: "Family time",
		priority: "important",
	},
	13: {
		date: "10.04.2023",
		title: "Wet Monday",
		note: "prepare a water gun",
		priority: "less important",
	},
	14: {
		date: "27.10.2023",
		title: "World Occupational Therapy Day.",
		note: "My work",
		priority: "less important",
	},
	15: {
		date: "03.12.2023",
		title: "Day of People with Disabilities",
		note: "Organizing an exhibition of works by people with disabilities",
		priority: "less important",
	},
	16: {
		date: "20.08.2023",
		title: "World Mosquito Day",
		note: "buy a deet preparation",
		priority: "common",
	},
	17: {
		date: "21.06.2023",
		title: "Poop night",
		note: "go to the fire",
		priority: "less important",
	},
	18: {
		date: "26.05.2023",
		title: "Mother's Day",
		note: "Buy flowers",
		priority: "important",
	},
	19: {
		date: "07.04.2023",
		title: "Beaver Day",
		note: "walk by the dams",
		priority: "common",
	},
	20: {
		date: "17.02.2023",
		title: "Cat Day",
		note: "petting a cat",
		priority: "important all year",
	},
};
document.querySelector("#eventTable").innerHTML = events;
